### ISSUE TITLE
SZ_ERROR_DATA when decompressing binary

### ISSUE THREAD

**Issue by TheNeverMan** [ilyazx/bzpwork#1]
When I try to decompress a stone bin command fails with triple:
Extracting [./kern.bin]
LZMA error [1 (SZ_ERROR_DATA))].
Extracting [./usr.bin]
LZMA error [1 (SZ_ERROR_DATA))].
Extracting [./res.bin]
LZMA error [1 (SZ_ERROR_DATA))].
Extract from stone image [SC6531EFM_sc6531efm_32X32_160X128BAR_AB_stone.bin] complete.
Here is log:
Extract [./kern.bin], copression CMP_LZMA_SPRD, pacsize = 212964
Extract [./usr.bin], copression CMP_LZMA_SPRD, pacsize = 4096
Extract [./res.bin], copression CMP_LZMA_SPRD, pacsize = 4096
Binary is stone.bin extracted from Alcatel 2003D pac firmware using spd research tool.
[binary.zip](https://github.com/ilyazx/bzpwork/files/7492370/binary.zip)

**Comment by ilyazx** [comment]
Hi! I have no error messages when unpacking the binary.bin file:

```
Extracting [./kern.bin]
[**************************************************]
Extracting [./usr.bin]
[**************************************************]
Extracting [./res.bin]
[**************************************************]
Extract from stone image [binary.bin] complete. 
```

```
Extract [./kern.bin], copression CMP_LZMA_SPRD, pacsize = 212964
Extract [./usr.bin], copression CMP_LZMA_SPRD, pacsize = 4096
Extract [./res.bin], copression CMP_LZMA_SPRD, pacsize = 4096
```

**Comment by TheNeverMan** [comment]
Ok actually I haven't said everything, my build of your program is using LZMA libs from https://github.com/sisong/lzma (of course the CPP ones) because building default ones results in:
``g++ -o bzpwork  Alloc.o LzFind.o LzmaDec.o LzmaEnc.o main.o  
/home/linuxbrew/.linuxbrew/bin/ld: LzmaDec.o: warning: relocation against `lzma_spd' in read-only section `.text'
/home/linuxbrew/.linuxbrew/bin/ld: LzmaDec.o: in function `LzmaDec_DecodeReal2(CLzmaDec*, unsigned long, unsigned char const*)':
LzmaDec.c:(.text+0x42a): undefined reference to `lzma_spd'
/home/linuxbrew/.linuxbrew/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status``
Here there are many "linuxbrew" references, but I have tried to compile bzpwork on plain Ubuntu amd64 virtual machine and it failed too. However when I replaced content of LZMA directory of bzpwork with https://github.com/sisong/lzma/tree/master/C, it compiled, but trying to decompress binary.bin failed with this error (SZ_ERROR_DATA).

**Comment by TheNeverMan** [comment]
I have managed to fix this, every "lzma_sprd" reference should be changed to "lzma_spd" (there is some mess with naming, sometimes its "lzma_sprd" sometimes "lzma_spd", this is why linker drops errors). After this everything perfectly compiles, and extraction works. Amazing tool by the way.
